# Generated by Django 3.1.7 on 2022-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='use',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
