# Generated by Django 3.1.7 on 2022-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220130_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
